CURATED_CARDS = [
    {
        "id": "seed-hdfc-millennia",
        "card_name": "HDFC Millennia",
        "issuer": "HDFC",
        "network": "Visa",
        "reward_rules": {
            "dining": 0.05,
            "groceries": 0.05,
            "shopping": 0.025,
            "travel": 0.01,
            "fuel": 0.01,
            "utilities": 0.01,
            "entertainment": 0.05,
            "others": 0.01,
        },
    },
    {
        "id": "seed-axis-flipkart",
        "card_name": "Axis Flipkart",
        "issuer": "Axis",
        "network": "Mastercard",
        "reward_rules": {
            "dining": 0.04,
            "groceries": 0.015,
            "shopping": 0.05,
            "travel": 0.015,
            "fuel": 0.015,
            "utilities": 0.015,
            "entertainment": 0.015,
            "others": 0.015,
        },
    },
    {
        "id": "seed-icici-amazon-pay",
        "card_name": "ICICI Amazon Pay",
        "issuer": "ICICI",
        "network": "Visa",
        "reward_rules": {
            "dining": 0.02,
            "groceries": 0.02,
            "shopping": 0.05,
            "travel": 0.01,
            "fuel": 0.01,
            "utilities": 0.01,
            "entertainment": 0.02,
            "others": 0.01,
        },
    },
]
